

services:
  # Frontend Vue
  frontend:
    build:
      context: .
      args:
        BUILD_MODE: development
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8000/api/v1}
    container_name: vue-frontend
    ports:
      - "8080:3000"  # Accedes por http://localhost:8080
    networks:
      - papermill-procurement_papermill-network
    restart: unless-stopped

networks:
  papermill-procurement_papermill-network:
    external: true