

services:
  # Frontend Vue
  frontend:
    build:
      context: .
      args:
        BUILD_MODE: development
    container_name: vue-frontend
    ports:
      - "8080:3000"  # Accedes por http://localhost:8080
    networks:
      - papermill-network
    restart: unless-stopped
  frontend-dev:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - papermill-network
networks:
  papermill-network:
    driver: bridge